const servicesData={"USA":{"الهجرة العائلية":{"رعاية الزوج/الزوجة":{docs:"شهادة الزواج، هوية الزوجين",fees:"$535",time:"8-12 شهر"}}},"Canada":{"الهجرة الاقتصادية":{"Express Entry":{docs:"اختبار لغة، تقييم شهادات",fees:"CAD 1325",time:"6-12 شهر"}}}};
const countrySelect=document.getElementById("countrySelect"),mainServiceSelect=document.getElementById("mainServiceSelect"),subServiceSelect=document.getElementById("subServiceSelect"),detailsBox=document.getElementById("serviceDetails");
window.onload=()=>{for(let c in servicesData){let opt=document.createElement("option");opt.value=c;opt.textContent=c;countrySelect.appendChild(opt);}};
function populateMainServices(){mainServiceSelect.innerHTML="<option>-- اختر الخدمة الرئيسية --</option>";subServiceSelect.innerHTML="<option>-- اختر الخدمة الفرعية --</option>";detailsBox.innerHTML="";const c=countrySelect.value;if(c){for(let main in servicesData[c]){let opt=document.createElement("option");opt.value=main;opt.textContent=main;mainServiceSelect.appendChild(opt);}}}
function populateSubServices(){subServiceSelect.innerHTML="<option>-- اختر الخدمة الفرعية --</option>";detailsBox.innerHTML="";const c=countrySelect.value,m=mainServiceSelect.value;if(c&&m){for(let sub in servicesData[c][m]){let opt=document.createElement("option");opt.value=sub;opt.textContent=sub;subServiceSelect.appendChild(opt);}}}
function showServiceDetails(){const c=countrySelect.value,m=mainServiceSelect.value,s=subServiceSelect.value;if(c&&m&&s){const d=servicesData[c][m][s];detailsBox.innerHTML=`<strong>المستندات:</strong> ${d.docs}<br><strong>الرسوم:</strong> ${d.fees}<br><strong>المدة:</strong> ${d.time}`;}}
function submitForm(){const name=document.getElementById("clientName").value,email=document.getElementById("clientEmail").value,phone=document.getElementById("clientPhone").value,c=countrySelect.value,m=mainServiceSelect.value,s=subServiceSelect.value;if(!name||!email||!phone||!c||!m||!s){alert("يرجى تعبئة جميع الحقول");return;}const caseId="ALH-"+new Date().toISOString().slice(0,10).replace(/-/g,"")+"-"+Math.floor(Math.random()*900+100);document.getElementById("cardCase").textContent="رقم الملف: "+caseId;document.getElementById("cardName").textContent="الاسم: "+name;document.getElementById("cardPhone").textContent="الهاتف: "+phone;document.getElementById("cardEmail").textContent="البريد: "+email;document.getElementById("cardCountry").textContent="الدولة: "+c;document.getElementById("cardService").textContent="الخدمة: "+m+" - "+s;document.getElementById("cardDate").textContent="تاريخ التقديم: "+new Date().toLocaleString();
const qr=new QRious({value:`https://wa.me/13139194272?text=Case%20ID:%20${caseId}`,size:80});document.getElementById("qrCode").src=qr.toDataURL();
document.getElementById("clientCard").style.display="block";gsap.from("#clientCard",{duration:1,y:100,opacity:0});document.getElementById("thankYouPopup").style.display="flex";}
function closePopup(){document.getElementById("thankYouPopup").style.display="none";}
function sendWhatsApp(){const msg=document.getElementById("cardCase").textContent+"\n"+document.getElementById("cardName").textContent+"\n"+document.getElementById("cardPhone").textContent;window.open(`https://wa.me/13139194272?text=${encodeURIComponent(msg)}`,'_blank');}
async function downloadPDF(){const{{jsPDF}}=window.jspdf;const doc=new jsPDF();doc.text("Alhijrah Services",10,10);doc.text(document.getElementById("cardCase").textContent,10,30);doc.text(document.getElementById("cardName").textContent,10,40);doc.text(document.getElementById("cardPhone").textContent,10,50);doc.text(document.getElementById("cardEmail").textContent,10,60);doc.save("Alhijrah_Case.pdf");}
const canvas=document.getElementById('bgCanvas');const ctx=canvas.getContext('2d');canvas.width=window.innerWidth;canvas.height=window.innerHeight;let stars=[];for(let i=0;i<200;i++){stars.push({x:Math.random()*canvas.width,y:Math.random()*canvas.height,r:Math.random()*2});}function drawStars(){ctx.clearRect(0,0,canvas.width,canvas.height);ctx.fillStyle='white';for(let s of stars){ctx.beginPath();ctx.arc(s.x,s.y,s.r,0,Math.PI*2);ctx.fill();}requestAnimationFrame(drawStars);}drawStars();